# Generated by Django 4.2.25 on 2025-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0086_activeproject_archive_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousaccess',
            name='hide_authors',
            field=models.BooleanField(default=False),
        ),
    ]
