# Generated by Django 4.2.22 on 2025-09-02 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0086_uploadagreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadagreement',
            name='accepted_by',
            field=models.ForeignKey(blank=True,
                                    help_text='The user who accepted this upload agreement',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
